---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    run_list:
    - recipe[yum]
  - name: ubuntu-12.04
    run_list:
    - recipe[apt]
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rack_user_test::create]
  - name: create_with_password
    run_list:
      - recipe[rack_user_test::create_with_password]
  - name: remove
    run_list:
      - recipe[rack_user_test::remove]
